DROP TABLE IF EXISTS EMPLOYEES;

CREATE TABLE EMPLOYEES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  email VARCHAR(50) DEFAULT NULL,
  role VARCHAR(20) DEFAULT 'non-admin',
  username VARCHAR(20) NOT NULL UNIQUE,
  password VARCHAR(12) NOT NULL
);